app/urls.py
from django.urls import path
from app.views.userView import user_login, user_logout, user_register
from app.views.deviceView import index, get_data, get_map_data, get_users, get_device_by_user, update_decice_by_user
app_name = "app"

urlpatterns = [
    path("", index, name="index"),
    path("login/", user_login, name="login"),
    path("register/", user_register, name="register"),
    path("get-data/", get_data, name='getData'),
    path("get-users/", get_users, name="getUser"),
    path("get-map-data/", get_map_data, name="getMapData"),
    path("get-device-by-user/", get_device_by_user, name="getDeviceByUser"),
    path("update-device-by-user/", update_decice_by_user, name="updateDeviceByUser"),
    path("logout/", user_logout, name="logout")
]

trackingmap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('app.urls')),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %} Map Tracking Web App {% endblock %}</title>
        
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/select/1.6.2/css/select.dataTables.min.css" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css" integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=" crossorigin=""/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.1/MarkerCluster.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.1/MarkerCluster.Default.css" />
        <link rel="stylesheet" type="text/css" href="{% static 'css/daterangepicker.css' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/sellect.min.css' %}">

        <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js" integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=" crossorigin=""></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.1/leaflet.markercluster.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.27.0/moment.min.js" integrity="sha512-rmZcZsyhe0/MAjquhTgiUcb4d9knaFc7b5xAfju483gbEXTkeJRUMIPk6s3ySZMYUHEcjKbjLjyddGWMrNEvZg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script type="text/javascript" src="{% static 'js/jquery.daterangepicker.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/sellect.min.js' %}"></script>

    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-11" style="text-align:right">
                    {% if request.user.is_authenticated %}
                        <span>Welcome, {{ request.user.first_name }}</span>
                    {% else %}
                        <span>You are not logged in</span>
                    {% endif %}
                </div>
                <div class="col-md-1" style="text-align:right">
                    <a href="{% url 'app:logout' %}">logout</a>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

app/templates/login.html
{% extends 'base.html' %}

{% block title %} Log in {% endblock %}

{% block content %}

{% if error %}
    <p>{{ error }}</p>
{% endif %}

<section class="vh-100 bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Log in</h2>
              
              <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Login</button>
                <p class="text-center text-muted mt-5 mb-0">Don't have an account? <a href="/register"
                    class="fw-bold text-body"><u>Register here</u></a></p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block title %} Main Page {% endblock %}

{% block content %}

<section class="vh-100">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
        <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                <div class="card" style="border-radius: 15px;">
                    <div class="card-body p-5">
                        <h2 class="text-uppercase text-center mb-5">User Register</h2>

                        <form method="post">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>
</section>
    
{% endblock %}